Add support for asnprintf to the MemoryLeakDetector
cpputest/cpputest pull request #1729
Opened 2022-12-15 20:18 UTC by AlanRosenthal

see: https://man7.org/linux/man-pages/man3/asprintf.3.html

2022-12-16 06:47 UTC, thetic requested changes
Clang-tidy warnings need to be addressed.
Build without C standard library needs to be repaired.
We need to get test coverage for this before we can consider merging.

2022-12-16 06:47 UTC, thetic commented on src/CppUTest/TestHarness_c.cpp
> +#include <stdio.h>
Direct reliance on the C standard library is not allowed in CppUTest.

2022-12-17 04:19 UTC, thetic commented on src/CppUTest/TestHarness_c.cpp
> +#include <stdio.h>
My intuition is that this feature does not belong in CppUTest, but rather in your own force include. I don't see anything in the implementation that requires it to be tightly integrated with CppUTest itself.

`asnprintf` is non-standard; its a GCC/Linux extension. CppUTest is focused on portability across old, embedded, and resource-constrained systems. `asnprintf` isn't portable and I don't see it as especially valuable for CppUTest's target use-cases.

That's just my opinion though.@basvodde, did you have thoughts?

2023-04-02 02:38 UTC, closed without merging

2023-04-03 12:22 UTC, basvodde commented
@AlanRosenthal Why close this?